### ISSUE TITLE
Documentacion

### ISSUE THREAD

**Issue by sjimenez44** [A4lfr32/ImageProcessing#1]
Excelente, ¿Qué vas hacer con este repositorio?

**Comment by alfredomaussa** [comment]
Hola Santiago, nada especial en realidad, solo quería dejarlo por acá como una plantilla en caso de que quiera aplicar `cv2.HoughLines()` en otra ocasión. Después se me olvida como era.

Es una respuesta que hice en stackoverflow y se me dio por por ponerla acá. De pronto ponga cosas similares.
